### PR TITLE
Split `AppTest` into `StructureTest` and `ElementOriginTest`

### LINKED ISSUE #69: Split `AppTest` into two tests for checking structure and origin
Reference: https://github.com/SpoonLabs/diffmin/pull/66#discussion_r644843865

Splitting the test case would make it easier for the developer to know if the test failed because of the incorrect structure or incorrect element origin.

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #69

### CODE REVIEW

**Comment by algomaster99** [comment]
This is the first draft. I am working on reducing code duplication. For example, the methods to run tests iteratively and this snippet below.

```java
File f1 = sources.prevPath.toFile();
File f2 = sources.newPath.toFile();
CtModel patchedCtModel = Main.patchAndGenerateModel(f1, f2);
```

**Comment by algomaster99** [comment]
To reduce the code duplication, I would have to combine `StructureTest` and `ElementOriginTest` which would just put us to back to where we started 😅 

I think we will have to iterate over the resources twice to run two `TestCase`s.

**Comment by slarse** [comment]
I will review this tomorrow, no time today.

**Comment by algomaster99** [comment]
No worries. Not very urgent.

**Review by slarse — APPROVED** [review]
LGTM. If you want to maximize cod reuse across tests, you could have a test base class with an abstract method `runTests(ResourceProvider.TestResources)`, and then just extend that and implement `runTests`.

You get code reuse at the expense of complexity, so its a tradeoff.

**Pull request merged**
