### PR TITLE
Add functionality for inserting case

### PR DESCRIPTION
**Pull request by algomaster99**
Changes add functionality to insert a case in `CtAbstractSwitch` which includes `CtSwitch` and `CtSwitchExpression`. However, the latter has not been tested because this language feature came about in Java 12 (standardised in v14) and we currently compile to Java SE 11.

To be merged after:
- [x] https://github.com/INRIA/spoon/issues/3884#issuecomment-869130820 is addressed.
- [x] https://github.com/INRIA/spoon/pull/4015 is merged. 
- [x] https://github.com/SpoonLabs/diffmin/issues/82 is resolved.

### CODE REVIEW

**Comment by algomaster99** [comment]
@slarse Marked it ready for review as the feature is working. I shall remove the workaround once https://github.com/INRIA/spoon/pull/4015 is merged.

**Review by slarse — COMMENTED** [review]
LGTM. But I suggest we wait with merging this Monday so we can use the new version of Spoon with the new method.

**Comment by slarse** [comment]
@algomaster is this done?

**Comment by algomaster99** [comment]
@slarse yes, we can merge this.

**Review by slarse — APPROVED** [review]

**Pull request merged**
