### PR TITLE
Compile test resources using Java 15

### LINKED ISSUE #82: Upgrading Java version
Currently, `diffmin` compiles to Java 11. I was thinking to upgrade it as it would allow incorporating more features of Java. For example, switch expressions. They were standardised in version 14. Moreover, `spoon` also supports up to Java 15.

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #82 

@slarse, I was not sure how to test using different Java versions inside a single job so I split them up. If there is a better way to achieve it, please let me know.

### CODE REVIEW

**Comment by slarse** [comment]
> @slarse, I was not sure how to test using different Java versions inside a single job so I split them up. If there is a better way to achieve it, please let me know.

You can run the `setup-java` action multiple times in the same job, for example:

```java
 test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15 for compiling test resources
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Verify if test resources compile
      run: ./scripts/verify-test-resource.sh

    - name: Set up JDK 11 for running tests
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Style check
      run: 'mvn spotless:check'
    - name: Run test phase
      run: mvn test
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
```

**Comment by algomaster99** [comment]
> You can run the setup-java action multiple times in the same job, for example:

I initially thought of this however, `java --version` could return either `11` or `15` after both versions are installed because we haven't explicitly configured which one to use and I am not sure how `action/setup-java` works. Either it could update `java` to point to `JDK 15` or not so it would be better to use `update-alternatives` command ourselves and specify which version to use.

**Comment by slarse** [comment]
> > You can run the setup-java action multiple times in the same job, for example:
> 
> Either it could update `java` to point to `JDK 15` or not so it would be better to use `update-alternatives` command ourselves and specify which version to use.

`setup-java` sets up the JDK to the version you specify, updating all necessary paths and variables. If you run it multiple times, it's the last run that counts. Note that there's almost always a default JDK even if you don't run `setup-java`, so if it didn't actually also set the "current" JDK, it wouldn't work at all.

You definitely don't want to run `update-alternatives` as that's specific to Debian, and if you then would like to run tests on macOS or Windows you're out of luck.

**Comment by algomaster99** [comment]
> setup-java sets up the JDK to the version you specify, updating all necessary paths and variables.

Thanks. I wasn't sure about this.

> Note that there's almost always a default JDK even if you don't run setup-java

We are running the job on `ubuntu-latest` which I don't think so has any JDK installed by default (at least I didn't have any JDK when I installed Ubuntu 20.04 on my system).

> it didn't actually also set the "current" JDK, it wouldn't work at all.

It should work, right? You are saying that a default JDK is present so `java` should point to the executable inside it.

**Comment by slarse** [comment]
> We are running the job on `ubuntu-latest` which I don't think so has any JDK installed by default (at least I didn't have any JDK when I installed Ubuntu 20.04 on my system).

The runner has some software pre-installed. [These are the pre-installed JDKs](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#java).

> > it didn't actually also set the "current" JDK, it wouldn't work at all.
> 
> It should work, right? You are saying that a default JDK is present so `java` should point to the executable inside it.

I meant that `setup-java` wouldn't work as intended if it only installed the specified version, but did not set it as the default. Then, the pre-installed default would still be the version used.

**Comment by slarse** [comment]
Do you want this as two separate jobs or to have them in one job? If the former, we can just merge now.

**Comment by algomaster99** [comment]
I will merge them in the next commit. I just split them because I wasn't sure if I could it in a single job.

**Comment by algomaster99** [comment]
@slarse Ready for merge.

**Comment by algomaster99** [comment]
@slarse Could you please merge this?

**Review by slarse — APPROVED** [review]

**Pull request merged**
